language: php

php:
    - 5.6
    - hhvm
env:
    - DB=mysql

before_script:
    - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hris;" -uroot; fi
    - composer self-update
    - composer install --prefer-source --no-interaction
    - chmod -R 777 storage
    - chmod -R 777 bootstrap/cache
    - cp .env.testing .env
    - php artisan migrate --env=testing --no-interaction -vvv
    - php artisan db:seed --env=testing --no-interaction -vvv

script: vendor/bin/phpunit
