language: php

php:
    - 5.5
    - 5.6
    - hhvm

env:
    - DB=mysql

before_script:
    - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hris;" -uroot; fi
    - composer self-update
    - composer install --prefer-source --no-interaction
    - chmod -R 777 storage
    - chmod -R 777 bootstrap/cache
    - cp .env.testing .env
    - php artisan migrate --env=testing --no-interaction -vvv
    - php artisan db:seed --env=testing --no-interaction -vvv

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

before_install:
    - pip install --user codecov

after_success:
    - codecov

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --access-token="e94508bbf4f71a23f390bddabce7d3faba1a240c287a28d939e6b9659882f398" --format=php-clover coverage.clover; fi
