language: php

php:
    - 5.6
    - hhvm
env:
    - DB=mysql

before_script:
    - cp .env.testing .env
    - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hris;" -uroot; fi
    - composer self-update
    - composer install --prefer-source --no-interaction
    - chmod -R 777 storage
    - chmod -R 777 bootstrap/cache
    - php artisan migrate --env=testing --no-interaction -vvv
    - php artisan db:seed --env=testing --no-interaction -vvv
    - php artisan serve --port=8080 &
    - npm install
    - npm install -g bower
    - npm install -g gulp
    - npm install -g laravel-elixir
    - bower install
    - gulp

script: phpunit
